### ISSUE TITLE
HypergeometricFunctions.drummond2F0 -> pFq

### ISSUE THREAD

**Issue by MikaelSlevinsky** [xzackli/ClenshawCurtisBessel.jl#2]
This is a friendly recommendation to convert all calls of `HypergeometricFunctions.drummond2F0` to `pFq`. For example, `drummond2F0(1/2+μ, 1/2-μ, -1/x; kmax=10_000Int(ceil(μ)))` should be `pFq((1/2+μ, 1/2-μ), (), -1/x)`, and the `kmax` keyword is now `2^20` by default. The tuples create no overhead and `pFq` calls more stable and efficient algorithms. There is no reason to call the internals anymore.

**Comment by xzackli** [comment]
Thanks, @MikaelSlevinsky! I'm very embarrassed you had to look in here, I really should archive this bit of numerical experimentation.

It's wonderful to see that HypergeometricFunctions has been tuple-ified. I can now deprecate a Weniger $_1F_2$ I had pasted from that package to deal with exactly that. Thanks for all your amazing work!
